modified:   app.js
DamianDawidowski/Phonebook_node pull request #3
Opened 2023-08-11 15:19 UTC by DamianDawidowski

modified:   models/contacts.js
 	modified:   package-lock.json
 	modified:   package.json
 	modified:   routes/contacts.js
 	new file:   service/contact.js

2023-08-11 15:25 UTC, DamianDawidowski commented
Testując na postman, GET mi nie działa, zwraca pustą tablicę [], mimo ze załadowałem oryginalny json w mongoDB Atlas i wyswietla sie poprawnie w Compass.

2023-08-11 19:12 UTC, RadziuMM requested changes
Mi działa możliwe że masz błędny link do logowania / albo masz w mongo źle nazwaną bazę danych z tego co masz w kodzie to powinno być ```contact```. U mnie wygląda to tak
```DB_HOST=mongodb+srv://username:paswword@cluster.abc123..mongodb.net/```

2023-08-11 19:12 UTC, RadziuMM commented on routes/contacts.js
> +const addContact = async (name, email, phone, favorite) => {
Tu przekazujesz cały obiekt więc musisz zrobić destrukturyzację tj objąć to w  "{ }"
```
const addContact = async ({ name, email, phone, favorite }) => { 
```

2023-08-11 19:12 UTC, RadziuMM commented on routes/contacts.js
> +  return await Contact.findOne({contactId})
Nie masz pola contactId w modelu a samo { contactId } jest skrótem od { contactId: contactId }
```
return await Contact.findOne({ _id: contactId })
```

2023-08-11 19:12 UTC, RadziuMM commented on routes/contacts.js
> +    return await Contact.findByIdAndRemove({contactId});
to samo co przy getById

2023-08-11 19:12 UTC, RadziuMM commented on routes/contacts.js
> +const updateContact = (contactId,  name, email, phone, favorite) => {
```
const updateContact = async (_id, payload) => {
	return Contact.findOneAndUpdate(_id, payload, {
		new: true,
	});
};
```

2023-08-11 19:12 UTC, RadziuMM commented on routes/contacts.js
W put przy wywołaniu  updateContact powinneś podać id zwrócone z bazy
```const updatedContact = updateContact(contact.id, req.body);```

2023-08-11 19:12 UTC, RadziuMM commented on app.js
> +    .then(() => console.log("Database connection successful: "+urlDb))
Raczej nie chcemy logować na serverze rzeczy z dotenv'a tym bardziej że w tym linku jest username i hasło

2023-08-12 16:21 UTC, DamianDawidowski commented
Dzięki, zrobiłem wszystkie korekty w nowym commit

2023-08-13 00:16 UTC, RadziuMM approved these changes

2023-08-17 08:49 UTC, merged