modified:   app.js
DamianDawidowski/Phonebook_node pull request #4
Opened 2023-08-19 08:30 UTC by DamianDawidowski

new file:   routes/authorization.js
 	new file:   service/authorization.js
 	new file:   service/user.js

2023-08-19 10:38 UTC, RadziuMM requested changes
1. Jak już kopiujesz z kogoś to musisz odpalić ten kod nawet po to by dowiedzieć się że masz niezainstalowane zależności (paczki za pomocą npm) bo teraz widać że nawet tego nie odpaliłeś....
2. W kilku miejscach masz exporty obiektów a importujesz je jak by była tam tylko 1 funkcja np
```
module.exports = { createUser, ....., router }
const authRouter = require("./routes/authorization"); // źle
const { router: authRouter } = require("./routes/authorization"); // dobrze
```
3. Kod nie jest sformatowany i się rozjeżdża.
4. W konsoli jeszcze wyskakuje kilka błędów które też trzeba naprawić

2023-08-19 19:38 UTC, DamianDawidowski commented
Zainstalowałem zależności, uporządkowałem kod i przetestowałem funkcje w Postman, wszystkie działają.

2023-08-20 10:32 UTC, RadziuMM requested changes

2023-08-20 10:32 UTC, RadziuMM commented on routes/routes.js
> +router.use("/users", authRouter);
router.use("/api/users", authRouter);

2023-08-20 10:32 UTC, RadziuMM commented on service/authorization.js
> +const auth = async (req, res, next) => {
Ogólnie to działa i nawet dobrze, ale chcemy zastosować tutaj strategię oraz użyć jedngo z bardziej znanych modeli tej strategii czyli bearer tokenu (Tak w skrócie jest to prawie to samo tylko że z przodu jest słówko Bearer)

Pokazane jak to zrobić masz na lms w materiałach Moduł 4 lekcja 7-8 autoryzacja jwt (tam praktycznie wystarczy to skopiować, jedyne co mususz dodać to sprawdzanie czy token w req będzie taki sam jak w w db bo tego przykład nie obejmuje)

2023-08-20 13:59 UTC, DamianDawidowski commented
Dodałem autoryzację jwt, testowałem i działa w Postman.

2023-08-20 16:36 UTC, RadziuMM approved these changes

2023-08-21 18:40 UTC, merged